name: Expresiones
run-name: Â¡Trabajando con expresiones!
on: 
  push:
    branches:
      - master
  pull_request:
     types:
       - opened
       - synchronize
       - reopened
  workflow_dispatch: 
      inputs:
          edad_persona:
            description: 'Edad de la persona'
            default: 18
            required: true
            type: number
          nombre_persona:
             description: 'Nombre persona'
             default: 'Juan'
             required: true
             type: string
jobs:
  mayor:
    if: ${{inputs.edad_persona >= 18}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: definir nombre
        run: echo "USERNAME=${{ inputs.nombre_persona }}" >> $GITHUB_ENV
      - name: definir edad
        run:  echo "Edad=${{ inputs.edad_persona}}" es mayor de edad
      - name: Correr Script
        run: python expresiones.py
  menor:
    if: ${{inputs.edad_persona <= 18}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: correr script
        run: echo ${{inputs.nombre_persona}} es menor de edad
          
