name: usando secretos
run-name: ¡Estoy aprendiendo a usar secretos!
on: 
  workflow_dispatch:
env:
  DIA_DE_SEMANA: Lunes
jobs:
  creando-variable:
   runs-on: ubuntu-latest
   env:
     SALUDO: Hola
   steps:
     - name: Saludar
       run: echo "$SALUDO, ${{vars.NOMBRE}}. ¡Hoy es ${{env.DIA_DE_SEMANA}}"
  creando-secretos:
   runs-on: ubuntu-latest
   env:
     SECRETO: TU
   steps:
     - name: Saludar
       run: echo "$SALUDO, ${{vars.NOMBRE}}"
     - name: Secreto
       run: echo "$SECRETO, ES ${{secrets.CONTRASENA}} "
