name: usando variables
run-name: ¡Estoy aprendiendo a usar variables!
on: 
  workflow_dispatch:
env:
  DIA_DE_SEMANA: Lunes
jobs:
  creando-variable:
   runs-on: ubuntu-latest
   env:
     SALUDO: Hola
   steps:
     - name: Saludar
       run: echo "$SALUDO, ${{NOMBRE}}. ¡Hoy es ${{env.DIA_DE_SEMANA}}"
       env:
         NOMBRE: Juan
